# Generated by Django 2.1.7 on 2019-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190311_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to='recipes.Recipe'),
        ),
    ]
