# Generated by Django 2.1.7 on 2019-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_author_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipes.Recipe'),
        ),
    ]
